name: "Submod Check"
description: "Perform a code check and headless MAS run on repository"

inputs:
  submod-path:
    description: >
      Path to directory containing submod script files. If not provided, action
      will detect its location automatically (might be inaccurate.)

runs:
  using: "composite"
  steps:
    - name: "Pull MDK"
      shell: "bash"
      run: |
        "${{ github.action_path }}/steps/install-mdk.sh" \
          "${{ github.action_path }}"

    - name: "Run checks"
      shell: "bash"
      env:
        SDL_AUDIODRIVER: dummy
      run: |
        "${{ github.action_path }}/steps/run-checks.sh" \
          "${{ github.action_path }}" \
          "${{ inputs.submod-path }}"